// Pure analysis behind `npm run images:audit` (Phase 32): compares the item_images rows with the
// objects actually in the bucket and summarises formats, sizes and problems. No I/O here.
import { extensionOf, formatBytes } from './imageMeta.mjs'

const FORMAT_BY_MIME = {
  'image/png': 'PNG',
  'image/jpeg': 'JPEG',
  'image/webp': 'WebP',
  'image/gif': 'GIF',
}
const FORMAT_BY_EXT = {
  png: 'PNG',
  jpg: 'JPEG',
  jpeg: 'JPEG',
  webp: 'WebP',
  gif: 'GIF',
}
export const SIZE_BANDS = [
  ['< 100 kB', 100e3],
  ['100–500 kB', 500e3],
  ['0.5–1 MB', 1e6],
  ['1–2 MB', 2e6],
  ['2–5 MB', 5e6],
  ['≥ 5 MB', Infinity],
]

export const formatOf = (object) =>
  FORMAT_BY_MIME[object.mimetype] ??
  FORMAT_BY_EXT[extensionOf(object.path)] ??
  (object.mimetype || 'unknown')

function tally(map, key, size) {
  const entry = map.get(key) ?? { count: 0, bytes: 0, max: 0 }
  entry.count += 1
  entry.bytes += size
  entry.max = Math.max(entry.max, size)
  map.set(key, entry)
}

/**
 * @param {{ rows: Array<{id: string, item_type: string, item_id: string, storage_path: string, is_cover: boolean}>,
 *           objects: Array<{path: string, size: number, mimetype: string, eTag: string, cacheControl: string}>,
 *           items: Array<{id: string, item_type: string}> }} input
 */
export function analyzeImages({ rows, objects, items }) {
  const objectByPath = new Map(objects.map((o) => [o.path, o]))
  const rowPaths = new Set(rows.map((r) => r.storage_path))

  const byFormat = new Map()
  const byType = new Map()
  const bands = new Map(SIZE_BANDS.map(([label]) => [label, 0]))
  const cacheControl = new Map()
  for (const o of objects) {
    tally(byFormat, formatOf(o), o.size)
    tally(byType, o.path.split('/')[0], o.size)
    const band = SIZE_BANDS.find(([, limit]) => o.size < limit)[0]
    bands.set(band, bands.get(band) + 1)
    cacheControl.set(
      o.cacheControl || '(none)',
      (cacheControl.get(o.cacheControl || '(none)') ?? 0) + 1,
    )
  }

  const pathCounts = new Map()
  for (const r of rows)
    pathCounts.set(r.storage_path, (pathCounts.get(r.storage_path) ?? 0) + 1)

  const contentGroups = new Map()
  for (const o of objects) {
    if (!o.eTag) continue
    const key = `${o.eTag}:${o.size}`
    contentGroups.set(key, [...(contentGroups.get(key) ?? []), o.path])
  }

  const itemKey = (type, id) => `${type}:${id}`
  const imagesPerItem = new Map()
  const coverPerItem = new Set()
  for (const r of rows) {
    const key = itemKey(r.item_type, r.item_id)
    imagesPerItem.set(key, (imagesPerItem.get(key) ?? 0) + 1)
    if (r.is_cover) coverPerItem.add(key)
  }

  return {
    totals: {
      rows: rows.length,
      objects: objects.length,
      bytes: objects.reduce((sum, o) => sum + o.size, 0),
      items: items.length,
      itemsWithImages: imagesPerItem.size,
    },
    byFormat: [...byFormat].sort((a, b) => b[1].bytes - a[1].bytes),
    byType: [...byType].sort((a, b) => b[1].bytes - a[1].bytes),
    bands: [...bands],
    cacheControl: [...cacheControl].sort((a, b) => b[1] - a[1]),
    largest: [...objects].sort((a, b) => b.size - a.size).slice(0, 10),
    rowsWithoutObject: rows.filter((r) => !objectByPath.has(r.storage_path)),
    objectsWithoutRow: objects.filter((o) => !rowPaths.has(o.path)),
    sharedPaths: [...pathCounts]
      .filter(([, n]) => n > 1)
      .map(([p, n]) => ({ path: p, rows: n })),
    duplicateContent: [...contentGroups.values()].filter(
      (paths) => paths.length > 1,
    ),
    pathMismatches: rows.filter((r) => {
      const [type, id] = r.storage_path.split('/')
      return type !== r.item_type || id !== r.item_id
    }),
    itemsWithoutImages: items.filter(
      (i) => !imagesPerItem.has(itemKey(i.item_type, i.id)),
    ).length,
    itemsWithoutCover: [...imagesPerItem.keys()].filter(
      (k) => !coverPerItem.has(k),
    ).length,
  }
}

const table = (head, body) =>
  [
    `| ${head.join(' | ')} |`,
    `| ${head.map(() => '---').join(' | ')} |`,
    ...body.map((r) => `| ${r.join(' | ')} |`),
  ].join('\n')

const list = (entries, render, max = 20) =>
  entries.length === 0
    ? 'None.'
    : [
        ...entries.slice(0, max).map((e) => `- ${render(e)}`),
        entries.length > max ? `- … and ${entries.length - max} more` : '',
      ]
        .filter(Boolean)
        .join('\n')

/** The docs/images-audit.md report. */
export function renderAuditMarkdown(a, generatedAt) {
  const t = a.totals
  const pct = (n) => `${((n / Math.max(t.bytes, 1)) * 100).toFixed(1)} %`
  return `# Image audit

Generated by \`npm run images:audit\` on ${generatedAt}. Metadata only (Storage list API + \`item_images\`), nothing downloaded.

## Totals

| What | Value |
| --- | --- |
| Items (\`all_items\`) | ${t.items} (${t.itemsWithImages} with images, ${a.itemsWithoutImages} without) |
| \`item_images\` rows | ${t.rows} |
| Storage objects (\`item-images\`) | ${t.objects} |
| Bucket size | **${formatBytes(t.bytes)}** (${t.bytes.toLocaleString('en-US')} bytes) |

## By format

${table(
  ['Format', 'Objects', 'Size', 'Share', 'Average', 'Largest'],
  a.byFormat.map(([f, e]) => [
    f,
    e.count,
    formatBytes(e.bytes),
    pct(e.bytes),
    formatBytes(e.bytes / e.count),
    formatBytes(e.max),
  ]),
)}

## By item type

${table(
  ['Type', 'Objects', 'Size', 'Share'],
  a.byType.map(([type, e]) => [
    type,
    e.count,
    formatBytes(e.bytes),
    pct(e.bytes),
  ]),
)}

## Size distribution

${table(
  ['File size', 'Objects'],
  a.bands.map(([label, n]) => [label, n]),
)}

## Cache-Control

${table(
  ['Header', 'Objects'],
  a.cacheControl.map(([value, n]) => [`\`${value}\``, n]),
)}

## Largest 10

${table(
  ['Path', 'Size', 'Type'],
  a.largest.map((o) => [`\`${o.path}\``, formatBytes(o.size), o.mimetype]),
)}

## Problems

- **Rows without an object** (broken images): ${a.rowsWithoutObject.length}
- **Objects without a row** (orphans, wasted space): ${a.objectsWithoutRow.length}${
    a.objectsWithoutRow.length
      ? ` — ${formatBytes(a.objectsWithoutRow.reduce((s, o) => s + o.size, 0))}`
      : ''
  }
- **Paths used by more than one row**: ${a.sharedPaths.length}
- **Identical files stored more than once** (same eTag + size): ${a.duplicateContent.length} group(s)
- **Rows whose path doesn't match their item** (\`{item_type}/{item_id}/…\`): ${a.pathMismatches.length}
- **Items with images but no cover**: ${a.itemsWithoutCover}

### Rows without an object

${list(a.rowsWithoutObject, (r) => `\`${r.storage_path}\` (row ${r.id})`)}

### Objects without a row

${list(a.objectsWithoutRow, (o) => `\`${o.path}\` — ${formatBytes(o.size)}`)}

### Duplicate content

${list(a.duplicateContent, (paths) => paths.map((p) => `\`${p}\``).join(', '))}

### Path mismatches

${list(a.pathMismatches, (r) => `\`${r.storage_path}\` → row says ${r.item_type}/${r.item_id}`)}
`
}
